pub mod common;
pub mod mario;
pub mod donkey;
pub mod link;
pub mod samus;
pub mod samusd;
pub mod yoshi;
pub mod kirby;
pub mod fox;
pub mod pikachu;
pub mod luigi;
pub mod ness;
pub mod captain;
pub mod purin;
pub mod peach;
pub mod daisy;
pub mod koopa;
pub mod popo;
pub mod nana;
pub mod sheik;
pub mod zelda;
pub mod mariod;
pub mod pichu;
pub mod falco;
pub mod marth;
pub mod lucina;
pub mod younglink;
pub mod ganon;
pub mod mewtwo;
pub mod roy;
pub mod chrom;
pub mod gamewatch;
pub mod metaknight;
pub mod pit;
pub mod pitb;
pub mod szerosuit;
pub mod wario;
pub mod snake;
pub mod ike;
pub mod pzenigame;
pub mod pfushigisou;
pub mod plizardon;
pub mod diddy;
pub mod lucas;
pub mod sonic;
pub mod dedede;
pub mod pikmin;
pub mod lucario;
pub mod robot;
pub mod toonlink;
pub mod wolf;



pub fn install() {
    common::install();
    mario::install();
    donkey::install();
    link::install();
    samus::install();
    samusd::install();
    yoshi::install();
    kirby::install();
    fox::install();
    pikachu::install();
    luigi::install();
    ness::install();
    captain::install();
    purin::install();
    peach::install();
    koopa::install();
    popo::install();
    nana::install();
    sheik::install();
    zelda::install();
    mariod::install();
    pichu::install();
    falco::install();    
    marth::install(); 
    lucina::install(); 
    younglink::install(); 
    ganon::install(); 
    mewtwo::install(); 
    roy::install(); 
    chrom::install(); 
    gamewatch::install(); 
    metaknight::install();
    pit::install();
    pitb::install();
    szerosuit::install();
    wario::install();
    snake::install();
    ike::install();
    pzenigame::install();
    pfushigisou::install();
    plizardon::install();
    diddy::install();
    lucas::install();
    sonic::install();
    dedede::install();
    pikmin::install();
    lucario::install();
    robot::install();
    toonlink::install();
    wolf::install();

}