#![feature(concat_idents)]
#![feature(proc_macro_hygiene)]
#![feature(asm)]

mod hooks;
mod lightning_01_common;
mod lightning_01_counter_cancels;
mod lightning_01_detector_boxes;
mod lightning_01_motioncancels;
mod lightning_01_crimson_cancel;
//mod lightning_01_lightning_mode_mechanics;
mod lightning_01_ultrainstinct2;
mod lightning_01_upbcancels;
mod lightning_01_upbtransitions;
mod lightning_01_edgecancelling;
mod lightning_02_up_special_callbacks;
mod lightning_01_lightning_fsmeter;
//mod lightning_01_vanish;
//mod lightning_02_params;
mod lightning_bayonetta;
mod lightning_brave;
mod lightning_buddy;
mod lightning_captain;
mod lightning_cloud;
mod lightning_dedede;
mod lightning_demon;
mod lightning_diddy;
mod lightning_dolly;
mod lightning_donkey;
mod lightning_duckhunt;
mod lightning_edge;
mod lightning_eflame;
mod lightning_elight;
mod lightning_falco_fox;
mod lightning_gamewatch;
mod lightning_ganon;
mod lightning_gaogaen;
mod lightning_gekkouga;
mod lightning_ike;
mod lightning_inkling;
mod lightning_jack;
mod lightning_kamui;
mod lightning_kirby;
mod lightning_koopa;
mod lightning_koopajr;
mod lightning_krool;
mod lightning_link;
mod lightning_littlemac;
mod lightning_lucario;
mod lightning_lucas;
mod lightning_luigi;
mod lightning_mario;
mod lightning_mariod;
mod lightning_marth_lucina;
mod lightning_master;
mod lightning_metaknight;
mod lightning_mewtwo;
mod lightning_mii;
mod lightning_murabito;
mod lightning_ness;
mod lightning_packun;
mod lightning_pacman;
mod lightning_palutena;
mod lightning_peach_daisy;
//mod lightning_pfushigisou;
mod lightning_pichu_pikachu;
mod lightning_pickel;
mod lightning_pikmin;
mod lightning_pit_pitb;
//mod lightning_plizardon;
mod lightning_pokemon_trainer;
mod lightning_popo_nana;
mod lightning_purin;
//mod lightning_pzenigame;
mod lightning_reflet;
mod lightning_ridley;
mod lightning_robot;
mod lightning_rockman;
mod lightning_rosetta;
mod lightning_roy_chrom;
mod lightning_ryu_ken;
mod lightning_samus_samusd;
mod lightning_sheik;
mod lightning_shizue;
mod lightning_shulk;
mod lightning_simon_richter;
mod lightning_snake;
mod lightning_sonic;
mod lightning_szerosuit;
mod lightning_tantan;
mod lightning_trail;
mod lightning_toonlink;
mod lightning_wario;
mod lightning_wiifit;
mod lightning_wolf;
mod lightning_yoshi;
mod lightning_younglink;
mod lightning_zelda;





#[skyline::main(name = "lightning")]
pub fn main() {
hooks::install();
lightning_01_common::install();
lightning_01_counter_cancels::install();
lightning_01_detector_boxes::install();
lightning_01_motioncancels::install();
//lightning_01_lightning_mode_mechanics::install();
lightning_01_lightning_fsmeter::install();
lightning_01_crimson_cancel::install();
lightning_01_ultrainstinct2::install();
lightning_01_upbcancels::install();
lightning_01_upbtransitions::install();
lightning_01_edgecancelling::install();
lightning_02_up_special_callbacks::install();
//lightning_01_vanish::install();
//lightning_02_params::install();
lightning_bayonetta::install();
lightning_brave::install();
lightning_buddy::install();
lightning_captain::install();
lightning_cloud::install();
lightning_dedede::install();
lightning_demon::install();
lightning_diddy::install();
lightning_dolly::install();
lightning_donkey::install();
lightning_duckhunt::install();
lightning_edge::install();
lightning_eflame::install();
lightning_elight::install();
lightning_falco_fox::install();
lightning_gamewatch::install();
lightning_ganon::install();
lightning_gaogaen::install();
lightning_gekkouga::install();
lightning_ike::install();
lightning_inkling::install();
lightning_jack::install();
lightning_kamui::install();
lightning_kirby::install();
lightning_koopa::install();
lightning_koopajr::install();
lightning_krool::install();
lightning_link::install();
lightning_littlemac::install();
lightning_lucario::install();
lightning_lucas::install();
lightning_luigi::install();
lightning_mario::install();
lightning_mariod::install();
lightning_marth_lucina::install();
lightning_master::install();
lightning_metaknight::install();
lightning_mewtwo::install();
lightning_mii::install();
lightning_murabito::install();
lightning_ness::install();
lightning_packun::install();
lightning_pacman::install();
lightning_palutena::install();
lightning_peach_daisy::install();
//lightning_pfushigisou::install();
lightning_pichu_pikachu::install();
lightning_pickel::install();
lightning_pikmin::install();
lightning_pit_pitb::install();
//lightning_plizardon::install();
lightning_pokemon_trainer::install();
lightning_popo_nana::install();
lightning_purin::install();
//lightning_pzenigame::install();
lightning_reflet::install();
lightning_ridley::install();
lightning_robot::install();
lightning_rockman::install();
lightning_rosetta::install();
lightning_roy_chrom::install();
lightning_ryu_ken::install();
lightning_samus_samusd::install();
lightning_sheik::install();
lightning_shizue::install();
lightning_shizue::install();
lightning_shulk::install();
lightning_simon_richter::install();
lightning_snake::install();
lightning_sonic::install();
lightning_szerosuit::install();
lightning_tantan::install();
lightning_toonlink::install();
lightning_trail::install();
lightning_wario::install();
lightning_wiifit::install();
lightning_wolf::install();
lightning_yoshi::install();
lightning_younglink::install();
lightning_zelda::install();

}